### ISSUE TITLE
Make jenkins-timeline-plugin discoverable

### ISSUE THREAD

**Issue by brandonbaksh** [tophat/jenkins-timeline-plugin#2]
**Is your feature request related to a problem? Please describe.**
I have no idea how to get this plugin for my jenkins build!

**Describe the solution you'd like**
I would like an easy way to download and install the jenkins-timeline-plugin

**Describe alternatives you've considered**
- some sort of install link and instructions to install
- make it available through jenkins plugin ui

**Additional context**
jenkins plugin ui
![screen shot 2018-11-19 at 9 33 43 am](https://user-images.githubusercontent.com/39271619/48713487-671cae00-ebde-11e8-9bf2-6df9bee466fd.png)

**Comment by jakebolam** [comment]
Following steps on: https://wiki.jenkins.io/display/JENKINS/Hosting+Plugins#HostingPlugins-Prerequisites

First step completed: https://issues.jenkins-ci.org/browse/HOSTING-669

**Comment by mcataford** [comment]
Bot checked out, waiting on human feedback from jenkinsci.

**Comment by mcataford** [comment]
As of this morning, permissions are set for Jenkins' Artifactory, I'll proceed with the last steps of the publishing process today. 🚀

**Comment by mcataford** [comment]
At last, JTL is on the [Jenkins Marketplace](https://plugins.jenkins.io/pipeline-timeline) 🚀
