### ISSUE TITLE
Create a timeline dashboard

### ISSUE THREAD

**Issue by brandonbaksh** [tophat/jenkins-timeline-plugin#3]
**Is your feature request related to a problem? Please describe.**
When clicking on the jenkins-timeline-plugin I don't see anything related to my build

**Describe the solution you'd like**
Create a dashboard interface that will break down the tasks of a jenkins build in a waterfall method.

**Additional context**
Example dashboard:
![screen shot 2018-11-19 at 9 35 57 am](https://user-images.githubusercontent.com/39271619/48713602-c1b60a00-ebde-11e8-94a4-a01b97e94e89.png)

**Comment by mcataford** [comment]
Feature implemented as of https://github.com/tophat/jenkins-timeline-plugin/pull/15.
