### ISSUE TITLE
Create an automated test suite

### ISSUE THREAD

**Issue by brandonbaksh** [tophat/jenkins-timeline-plugin#4]
**Is your feature request related to a problem? Please describe.**
I don't have confidence in the test coverage of jenkins-timeline-plugin

**Describe the solution you'd like**
Create a complete and automated test suite for jenkins-timeline-plugin for java and javascript

**Comment by mcataford** [comment]
https://github.com/tophat/jenkins-timeline-plugin/pull/17 covers Java tests, node tests to come when the node app is up. Putting this in blocked until then.

**Comment by mcataford** [comment]
Coverage added + added to CI as of #25
