### ISSUE TITLE
The timeline doesn't fill the whole screen

### ISSUE THREAD

**Issue by mcataford** [tophat/jenkins-timeline-plugin#43]
**Describe the bug**
The timeline component only occupies 200px of the screen height-wise.

**To Reproduce**
Open a pipeline with enough stages to potentially fill the screen with chart rows.

**Expected behavior**
The timeline should occupy as much space as it needs.

**Desktop (please complete the following information):**
 - OS: OSX, Chrome/Safari/Firefox
 - Release 1.0.0

**Comment by jakebolam** [comment]
Fixed by #44
